"""initial

Revision ID: 90fd7ecbbfd8
Revises: 
Create Date: 2024-07-06 15:15:35.968076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90fd7ecbbfd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('foto', sa.Text(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('current_position', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artikel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jasmani',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_siswa', sa.String(length=180), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=50), nullable=False),
    sa.Column('nilai_lari', sa.String(length=20), nullable=False),
    sa.Column('nilai_pullup', sa.String(length=20), nullable=True),
    sa.Column('nilai_situp', sa.String(length=20), nullable=False),
    sa.Column('nilai_pushup', sa.String(length=20), nullable=False),
    sa.Column('nilai_shutrun', sa.String(length=20), nullable=False),
    sa.Column('nilai_renang', sa.String(length=20), nullable=False),
    sa.Column('nilai_akhir', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keunggulan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layanan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('foto', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('alamat', sa.String(length=150), nullable=True),
    sa.Column('site_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keyword', sa.Text(), nullable=True),
    sa.Column('logo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_fasilitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_media_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wa', sa.String(length=20), nullable=True),
    sa.Column('instagram', sa.String(length=250), nullable=True),
    sa.Column('tiktok', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=60), nullable=False),
    sa.Column('lastname', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('visitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitor')
    op.drop_table('user')
    op.drop_table('social_media_link')
    op.drop_table('program_fasilitas')
    op.drop_table('profil')
    op.drop_table('layanan')
    op.drop_table('keunggulan')
    op.drop_table('jasmani')
    op.drop_table('artikel')
    op.drop_table('alumni')
    # ### end Alembic commands ###
